# .cnb.yml
$:
  vscode:
    - docker:
        #  build: .ide/Dockerfile
        # 指定开发环境的代码服务端口
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        image: docker.cnb.cool/tryxd/default-build-env

      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: ls
          script: ls -al
        - name: echo
          script:
            - echo "Hello, CNB!"
            - echo "This is a sample development environment."
            - npm -v

main:
  push:
    - services:
        - docker
      stages:
        - name: 导入密钥
          imports:
            - https://cnb.cool/tryxd/secret/-/blob/main/env.yml
          script: |
            docker run --rm \
              -e PLUGIN_TARGET_URL="https://github.com/x-dr/web-modem.git" \
              -e PLUGIN_AUTH_TYPE="https" \
              -e PLUGIN_USERNAME=${GIT_USERNAME} \
              -e PLUGIN_PASSWORD=${GIT_ACCESS_ACTION_TOKEN} \
              -e PLUGIN_BRANCH="main" \
              -e PLUGIN_FORCE="true" \
              -v $(pwd):$(pwd) \
              -w $(pwd) \
              tencentcom/git-sync